import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../core/env.dart';
import '../../../core/i18n/i18n.dart';
import '../../../core/routing/routes.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_radii.dart';
import '../../../core/theme/app_spacing.dart';
import '../../../core/theme/app_typography.dart';
import '../../../core/widgets/widgets.dart';
import '../data/bio_drafter_service.dart';
import '../domain/onboarding_draft.dart';
import '../providers/onboarding_draft_notifier.dart';
import 'stepper_layout.dart';

/// Step 4 of 5 — AI-assisted bio drafting.
///
/// Renders 2-3 selectable headline+bio variants generated by the Anthropic
/// API (`claude-haiku-4-5`). When the API key is absent / the call fails /
/// parsing fails, the step falls back to a deterministic local template so
/// the wizard never blocks on network availability.
class BioDraftStep extends ConsumerStatefulWidget {
  const BioDraftStep({super.key});

  @override
  ConsumerState<BioDraftStep> createState() => _BioDraftStepState();
}

class _BioDraftStepState extends ConsumerState<BioDraftStep> {
  /// Variants offered to the user. Index 0 is always the deterministic
  /// template (the always-available fallback); AI-generated variants are
  /// appended once the API call resolves.
  List<BioDraftVariant> _variants = const <BioDraftVariant>[];

  /// Index of the currently selected variant, or `null` if the user hasn't
  /// picked one yet (the "Looks good →" button is disabled in that case).
  int? _selectedIndex;

  /// `true` while the API call is in flight.
  bool _drafting = false;

  /// `true` once we've kicked off the API call so we don't re-fire on
  /// rebuilds (e.g. when the draft provider's AsyncValue ticks).
  bool _draftRequested = false;

  /// Visible only for unit tests — when set, the step uses [_testService]
  /// instead of building one from [Env.anthropicApiKey].
  @visibleForTesting
  static BioDrafterService? testServiceOverride;

  @override
  Widget build(BuildContext context) {
    final AsyncValue<OnboardingDraft> draftAsync =
        ref.watch(onboardingDraftProvider);
    final OnboardingDraft? draft = draftAsync.value;
    if (draft == null) {
      return const StepperLayout(
        stepIndex: 3,
        stepNameKey: 'onboarding.stepName.bio',
        child: Center(child: CircularProgressIndicator()),
      );
    }

    // Seed the variants list with the deterministic fallback on the first
    // build that sees a hydrated draft, and kick off the API call exactly
    // once. Subsequent rebuilds reuse whatever state we've accumulated.
    if (!_draftRequested) {
      _draftRequested = true;
      final BioDraftVariant fallback = _templateVariantFor(context, draft);
      _variants = <BioDraftVariant>[fallback];
      _selectedIndex = null;
      _maybeRequestAiVariants(draft);
    }

    final AppColors colors = Theme.of(context).extension<AppColors>()!;
    final AppRadii radii = Theme.of(context).extension<AppRadii>()!;
    final AppSpacing spacing = Theme.of(context).extension<AppSpacing>()!;
    final AppTypography typo = Theme.of(context).extension<AppTypography>()!;

    void advance() => context.go(Routes.onboardingAbout);

    Future<void> acceptSelected() async {
      final int? idx = _selectedIndex;
      if (idx == null) return;
      final BioDraftVariant chosen = _variants[idx];
      await ref
          .read(onboardingDraftProvider.notifier)
          .updateHeadline(chosen.headline);
      await ref.read(onboardingDraftProvider.notifier).updateBio(chosen.bio);
      if (!mounted) return;
      advance();
    }

    return StepperLayout(
      stepIndex: 3,
      stepNameKey: 'onboarding.stepName.bio',
      onBack: () => context.go(Routes.onboardingRoles),
      footer: AppButton(
        key: const ValueKey<String>('bio-looks-good'),
        label: context.t('onboarding.bio.looksGood'),
        variant: AppButtonVariant.gold,
        // Disabled until the user has selected a variant — and surface
        // the disabled visual so the tap doesn't read as broken.
        disabled: _selectedIndex == null,
        onPressed: _selectedIndex == null ? null : acceptSelected,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text(
            context.t('onboarding.bio.title'),
            style: typo.displayLg.copyWith(color: colors.navy),
          ),
          SizedBox(height: spacing.card / 2),
          Text(
            context.t('onboarding.bio.subtitle'),
            style: typo.bodyMd.copyWith(color: colors.muted),
          ),
          SizedBox(height: spacing.card),
          // Chat-thread bubble explaining what's happening.
          Container(
            key: const ValueKey<String>('bio-ai-bubble'),
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
            decoration: BoxDecoration(
              color: colors.white,
              borderRadius: BorderRadius.circular(radii.button),
              border: Border.all(color: colors.border, width: 1),
            ),
            child: RichText(
              text: TextSpan(
                style: typo.bodyMd.copyWith(color: colors.body),
                children: <InlineSpan>[
                  TextSpan(
                    text: 'AI: ',
                    style: typo.displaySm.copyWith(color: colors.navy),
                  ),
                  TextSpan(text: context.t('onboarding.bio.aiBubble')),
                ],
              ),
            ),
          ),
          SizedBox(height: spacing.card),
          // Loading indicator — visible while the API call is in flight.
          if (_drafting)
            Padding(
              key: const ValueKey<String>('bio-drafting'),
              padding: const EdgeInsets.only(bottom: 12),
              child: Row(
                children: <Widget>[
                  SizedBox(
                    width: 14,
                    height: 14,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      valueColor:
                          AlwaysStoppedAnimation<Color>(colors.muted),
                    ),
                  ),
                  const SizedBox(width: 8),
                  Text(
                    context.t('onboarding.bio.drafting'),
                    style: typo.bodyMd.copyWith(color: colors.muted),
                  ),
                ],
              ),
            ),
          Text(
            context.t('onboarding.bio.variantsHeading'),
            style: typo.bodyXs.copyWith(
              color: colors.muted,
              fontWeight: FontWeight.w600,
              letterSpacing: 1,
            ),
          ),
          const SizedBox(height: 8),
          // Variant cards.
          ...List<Widget>.generate(_variants.length, (int i) {
            return Padding(
              padding: EdgeInsets.only(
                bottom: i == _variants.length - 1 ? 0 : 8,
              ),
              child: _VariantCard(
                key: ValueKey<String>('bio-variant-$i'),
                variant: _variants[i],
                selected: _selectedIndex == i,
                onTap: () => setState(() => _selectedIndex = i),
              ),
            );
          }),
          SizedBox(height: spacing.card / 2),
          // "Write my own" skip link — always available, even while drafting.
          Align(
            alignment: Alignment.centerLeft,
            child: TextButton(
              key: const ValueKey<String>('bio-write-my-own'),
              onPressed: advance,
              style: TextButton.styleFrom(
                padding: EdgeInsets.zero,
                minimumSize: const Size(0, 0),
                tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                foregroundColor: colors.navy,
              ),
              child: Text(
                context.t('onboarding.bio.writeMyOwn'),
                style: typo.bodyMd.copyWith(
                  color: colors.navy,
                  decoration: TextDecoration.underline,
                ),
              ),
            ),
          ),
          SizedBox(height: spacing.card / 2),
          // Privacy footnote.
          Text(
            context.t('onboarding.bio.privacyNote'),
            style: typo.bodyXs.copyWith(color: colors.muted),
          ),
        ],
      ),
    );
  }

  /// Fires the Anthropic API call when a key is available. Failures fall back
  /// silently to the template variant that's already in [_variants].
  Future<void> _maybeRequestAiVariants(OnboardingDraft draft) async {
    final BioDrafterService? service = testServiceOverride ??
        BioDrafterService.clientFor(Env.anthropicApiKey);
    if (service == null) return;

    final String roleLabel = _roleLabel(context, draft);
    final String goalText = draft.goalText.trim();
    final String? goalLabel = draft.goalType != null
        ? context.t(draft.goalType!.i18nLabelKey)
        : null;

    if (!mounted) return;
    setState(() => _drafting = true);

    try {
      final List<BioDraftVariant> aiVariants = await service.draft(
        roleLabel: roleLabel,
        goalText: goalText,
        goalLabel: goalLabel,
      );
      if (!mounted) return;
      if (aiVariants.isEmpty) return;
      setState(() {
        _variants = aiVariants;
        _selectedIndex = null;
      });
    } on Object {
      // Any failure (network, parse, schema) — keep the fallback template in
      // _variants and let the user proceed with it.
    } finally {
      if (mounted) setState(() => _drafting = false);
    }
  }
}

/// Resolves the user-facing label for the draft's primary role. Falls back to
/// the raw key if no translation is available so the prompt context is never
/// silently dropped.
String _roleLabel(BuildContext context, OnboardingDraft draft) {
  final String roleKey =
      draft.primaryRole ?? (draft.roles.isNotEmpty ? draft.roles.first : '');
  if (roleKey.isEmpty) return '';
  return context.t('onboarding.roles.$roleKey');
}

/// Builds the deterministic template variant used as the always-available
/// fallback. Format:
///   headline: `RoleName · <truncated goal>`
///   bio:      `RoleName (<goalLabel>) — <full goal text>`
///
/// Falls back to safe i18n strings if either roles or goal text is missing.
BioDraftVariant _templateVariantFor(
  BuildContext context,
  OnboardingDraft draft,
) {
  final String roleLabel = _roleLabel(context, draft);
  final String goal = draft.goalText.trim();

  String headline;
  if (roleLabel.isEmpty && goal.isEmpty) {
    headline = context.t('onboarding.bio.fallbackHeadline');
  } else if (goal.isEmpty) {
    headline = roleLabel;
  } else if (roleLabel.isEmpty) {
    headline = _truncate(goal, 80);
  } else {
    headline = '$roleLabel · ${_truncate(goal, 80 - roleLabel.length - 3)}';
  }
  headline = _truncate(headline, 120);

  String bio;
  if (roleLabel.isEmpty && goal.isEmpty) {
    bio = context.t('onboarding.bio.fallbackBio');
  } else if (goal.isEmpty) {
    bio = '$roleLabel on BVisionRY Connect.';
  } else if (roleLabel.isEmpty) {
    bio = 'Looking for: $goal';
  } else {
    bio = '$roleLabel — looking for: $goal';
    if (draft.goalType != null) {
      final String goalLabel =
          context.t(draft.goalType!.i18nLabelKey).toLowerCase();
      bio = '$roleLabel ($goalLabel) — $goal';
    }
  }
  return BioDraftVariant(headline: headline, bio: bio);
}

String _truncate(String value, int max) {
  if (value.length <= max) return value;
  if (max <= 1) return value.substring(0, max);
  return '${value.substring(0, max - 1).trimRight()}…';
}

/// Tappable card showing one (headline, bio) variant. Gold-bordered when
/// selected, plain-bordered otherwise.
class _VariantCard extends StatelessWidget {
  const _VariantCard({
    super.key,
    required this.variant,
    required this.selected,
    required this.onTap,
  });

  final BioDraftVariant variant;
  final bool selected;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final AppColors colors = Theme.of(context).extension<AppColors>()!;
    final AppRadii radii = Theme.of(context).extension<AppRadii>()!;
    final AppTypography typo = Theme.of(context).extension<AppTypography>()!;

    final Color borderColor = selected ? colors.gold : colors.border;
    final double borderWidth = selected ? 2 : 1;
    final Color background = selected ? colors.goldPale : colors.white;

    return Semantics(
      button: true,
      selected: selected,
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(radii.button),
        child: Container(
          width: double.infinity,
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
          decoration: BoxDecoration(
            color: background,
            borderRadius: BorderRadius.circular(radii.button),
            border: Border.all(color: borderColor, width: borderWidth),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Text(
                variant.headline,
                style: typo.bodyMd.copyWith(
                  color: colors.navy,
                  fontWeight: FontWeight.w700,
                ),
              ),
              const SizedBox(height: 4),
              Text(
                variant.bio,
                maxLines: 2,
                overflow: TextOverflow.ellipsis,
                style: typo.bodyMd.copyWith(color: colors.body),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
