// Keep in sync with the `@theme` block in `global.css`.
// global.css is the source for Tailwind utilities (Tailwind v4 is CSS-first);
// this file is the source for direct TS/JSX usage (e.g. TextInput placeholderTextColor).
export const colors = {
  navy: '#0f3460',
  navyLight: '#1a4a80',
  navyDark: '#0a2340',
  gold: '#ffc107',
  goldLight: '#ffe187',
  goldPale: '#fff8e1',
  bg: '#f8f8f8',
  white: '#ffffff',
  text: '#212529',
  muted: '#94a3b8',
  border: '#e5e7eb',
  slate100: '#f1f5f9',
  slate300: '#cbd5e1',
  successBg: '#dcfce7',
  success: '#15803d',
  successBorder: '#4ade80',
  warningBg: '#fef3c7',
  warning: '#b45309',
  warningBorder: '#fbbf24',
  dangerBg: '#fee2e2',
  danger: '#b91c1c',
  dangerBorder: '#ef4444',
  infoBg: '#dbeafe',
  info: '#1d4ed8',
  infoBorder: '#93c5fd',
} as const;
