/**
 * Helpers for interacting with the local Mailpit instance that ships with the
 * Supabase CLI. Mailpit replaces Inbucket and exposes its own HTTP API on the
 * same port (54324).
 *
 * Magic-link emails generated by Supabase look like:
 *   http://127.0.0.1:54321/auth/v1/verify?token=...&type=magiclink&redirect_to=...
 * Following that URL triggers Supabase's verify endpoint, which then redirects
 * to the app URL with `#access_token=...&refresh_token=...` in the fragment.
 */

const MAILPIT_BASE = 'http://127.0.0.1:54324';

type MailpitSearchResponse = {
  total: number;
  unread: number;
  count: number;
  messages: Array<{
    ID: string;
    From: { Name: string; Address: string };
    To: Array<{ Name: string; Address: string }>;
    Subject: string;
    Snippet: string;
    Created: string;
  }>;
};

type MailpitMessage = {
  ID: string;
  From: { Name: string; Address: string };
  To: Array<{ Name: string; Address: string }>;
  HTML: string;
  Text: string;
  Subject: string;
};

/**
 * Polls Mailpit until a magic-link email arrives for the given recipient and
 * returns the verify URL embedded in the email body.
 */
export async function waitForMagicLink(email: string, timeoutMs = 30_000): Promise<string> {
  const deadline = Date.now() + timeoutMs;
  let lastError: unknown = null;

  while (Date.now() < deadline) {
    try {
      const searchRes = await fetch(
        `${MAILPIT_BASE}/api/v1/search?query=${encodeURIComponent(`to:${email}`)}&limit=10`
      );
      if (searchRes.ok) {
        const data = (await searchRes.json()) as MailpitSearchResponse;
        const latest = data.messages?.[0];
        if (latest) {
          const msgRes = await fetch(`${MAILPIT_BASE}/api/v1/message/${latest.ID}`);
          if (msgRes.ok) {
            const msg = (await msgRes.json()) as MailpitMessage;
            const link = extractMagicLink(msg.HTML || msg.Text);
            if (link) return link;
          }
        }
      }
    } catch (e) {
      lastError = e;
    }
    await new Promise((r) => setTimeout(r, 500));
  }

  throw new Error(
    `No magic link arrived for '${email}' within ${timeoutMs}ms` +
      (lastError ? ` (last error: ${String(lastError)})` : '')
  );
}

/**
 * Extracts the Supabase verify URL from email content. The link looks like
 *   http://127.0.0.1:54321/auth/v1/verify?token=...&type=magiclink&redirect_to=...
 * HTML emails encode `&` as `&amp;`, so we decode common entities before matching.
 */
export function extractMagicLink(content: string): string | null {
  if (!content) return null;
  const decoded = content.replace(/&amp;/g, '&');

  // Prefer the Supabase verify URL — it's the actual magic-link endpoint.
  const verifyMatch = decoded.match(/https?:\/\/[^\s"'<>]+\/auth\/v1\/verify\?[^\s"'<>]+/i);
  if (verifyMatch) return verifyMatch[0];

  // Fall back to any URL with a hash fragment (e.g. direct access_token links).
  const hashMatch = decoded.match(/https?:\/\/[^\s"'<>]+#[^\s"'<>]+/);
  if (hashMatch) return hashMatch[0];

  // Last-resort: any URL with a token-like query string.
  const queryMatch = decoded.match(/https?:\/\/[^\s"'<>]+\?[^\s"'<>]*token=[^\s"'<>]+/);
  if (queryMatch) return queryMatch[0];

  return null;
}

/**
 * Wipes every message from the local Mailpit inbox so tests start clean.
 */
export async function purgeAllMessages(): Promise<void> {
  await fetch(`${MAILPIT_BASE}/api/v1/messages`, { method: 'DELETE' });
}
