import 'dart:convert';
import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

/// RFC 5545 UTC timestamp helper: `YYYYMMDDTHHmmssZ`. Always UTC.
///
/// `DTSTART` / `DTEND` / `DTSTAMP` values use this format because the
/// VCALENDAR generated by [IcsService.generateIcsFile] doesn't ship a
/// VTIMEZONE block — every wall-clock translation is the calendar
/// client's job.
String formatICSDate(DateTime d) {
  final u = d.toUtc();
  String two(int n) => n.toString().padLeft(2, '0');
  return '${u.year.toString().padLeft(4, '0')}'
      '${two(u.month)}${two(u.day)}T${two(u.hour)}${two(u.minute)}'
      '${two(u.second)}Z';
}

/// Escape per RFC 5545 §3.3.11.
///
/// Backslash MUST be escaped first so a downstream replace doesn't
/// double-escape its own substitution: `\;` would become `\\;` if we did
/// it last.
String escapeICS(String input) {
  return input
      .replaceAll('\\', r'\\')
      .replaceAll(';', r'\;')
      .replaceAll(',', r'\,')
      .replaceAll('\n', r'\n');
}

/// Fold a single logical line at ≤75 OCTETS per physical line
/// (RFC 5545 §3.1). Continuation lines start with a single space (0x20).
///
/// IMPORTANT: the 75-byte limit is measured in UTF-8 OCTETS, not Dart
/// String code units. For multi-byte codepoints (emojis, accented
/// characters, snowmen) we walk back to a codepoint boundary so a fold
/// never splits a UTF-8 sequence — otherwise the resulting `.ics` file
/// would be rejected by strict parsers.
String foldLine(String line) {
  final bytes = utf8.encode(line);
  if (bytes.length <= 75) return line;

  final buffer = StringBuffer();
  var start = 0;
  var first = true;
  while (start < bytes.length) {
    // Continuation lines reserve 1 octet for the leading space; the
    // first line can use the full 75 bytes.
    final limit = first ? 75 : 74;
    var end = (start + limit) > bytes.length ? bytes.length : start + limit;

    // Walk back to a codepoint boundary if necessary: UTF-8 continuation
    // bytes have the high two bits set to `10xxxxxx` (0x80..0xBF). When
    // `end` lands on a continuation byte, step back until we hit a lead
    // byte (or hit `start`, in which case there's nothing to fold).
    while (end < bytes.length && (bytes[end] & 0xC0) == 0x80) {
      end -= 1;
    }

    final chunk = utf8.decode(bytes.sublist(start, end));
    if (first) {
      buffer.write(chunk);
      first = false;
    } else {
      buffer
        ..write('\r\n')
        ..write(' ')
        ..write(chunk);
    }
    start = end;
  }
  return buffer.toString();
}

/// Builds and shares RFC 5545 `.ics` files for confirmed meetings.
///
/// Pure helpers ([formatICSDate], [escapeICS], [foldLine]) are exported as
/// top-level functions so they can be unit-tested in isolation; the
/// stateful methods ([generateIcsFile], [shareIcs]) live on the class.
class IcsService {
  /// Build an RFC 5545 .ics file in the OS temp dir and return the [File].
  ///
  /// All lines are CRLF-terminated and folded at ≤75 octets. The UID is
  /// stable across regenerations (`meeting-${meetingId}@bvisionry.com`) so
  /// re-importing the file updates the existing calendar entry rather than
  /// creating a duplicate.
  ///
  /// File name: `meeting-{shortId}.ics` where `shortId` is the first 8
  /// chars of the meeting id — keeps the filename short while remaining
  /// unique enough to disambiguate concurrent shares.
  Future<File> generateIcsFile({
    required String meetingId,
    required String title,
    required String description,
    required DateTime startUtc,
    required DateTime endUtc,
    required List<String> attendeesEmails,
    required String? location,
  }) async {
    final lines = <String>[
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//BVisionry//Connect//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'BEGIN:VEVENT',
      'UID:meeting-$meetingId@bvisionry.com',
      'DTSTAMP:${formatICSDate(DateTime.now().toUtc())}',
      'DTSTART:${formatICSDate(startUtc)}',
      'DTEND:${formatICSDate(endUtc)}',
      'SUMMARY:${escapeICS(title)}',
      'DESCRIPTION:${escapeICS(description)}',
      if (location != null && location.isNotEmpty)
        'LOCATION:${escapeICS(location)}',
      ...attendeesEmails.map((e) {
        final safe = escapeICS(e);
        return 'ATTENDEE;CN=$safe:mailto:$safe';
      }),
      'END:VEVENT',
      'END:VCALENDAR',
    ];

    final folded = lines.map(foldLine).join('\r\n');
    final body = '$folded\r\n';

    final dir = await getTemporaryDirectory();
    final outDir = Directory('${dir.path}/meetings');
    if (!outDir.existsSync()) outDir.createSync(recursive: true);
    final shortId =
        meetingId.length >= 8 ? meetingId.substring(0, 8) : meetingId;
    final file = File('${outDir.path}/meeting-$shortId.ics');
    await file.writeAsString(body, encoding: utf8, flush: true);
    return file;
  }

  /// Share the generated `.ics` via the platform sheet using `share_plus`.
  Future<void> shareIcs(File file, {String? subject}) async {
    await Share.shareXFiles(
      <XFile>[XFile(file.path, mimeType: 'text/calendar')],
      subject: subject,
    );
  }
}
